### ISSUE TITLE
Delete HourGlassConfig.py and Wires.py after the synchronization

### ISSUE THREAD

**Issue by pwittich** [cms-L1TK/project_generation_scripts#21]
after [PR 141 of the firmware_hls repo is closed](https://github.com/cms-L1TK/firmware-hls/pull/141 )

also update the readme to show where this file comes from

**Comment by tomalin** [comment]
Since https://github.com/cms-L1TK/firmware-hls/pull/141 has been merged, I've created PR https://github.com/cms-L1TK/project_generation_scripts/pull/29 to solve the issues raised here.
